// Picklists and export configuration for the event reporting module.
// Site and contractor values mirror the importable-file dropdowns exactly so
// that exported files map back to the upstream import template.

export const SITE_OPTIONS: string[] = [
  '1100000094-4100001496 [Shapoorji] Pallonji',
  '4800000823 [Al Fahd Earthwork]Zone C Bulk Earthworks and Retaining Walls for OXAGON Port Development',
  '4800000796 [TAMIMI-AMT] D&B of Community School Grade 1-12 with ECC and Type A Offices',
  '4800000876 [Archirodon] Design and Build for OXAGON Terminal 2 (T2) Dredging and Quay Walls-D&B',
  '4800000882 [AL-FAHD] South Business Community High Density Expansion',
  '4800000892 [TDP] Highway 55 Upgrade - Cut & Cover Tunnel Earthworks',
  '4800000838 [SIBS] OXAGON South Business Community Expansion - Package 1 Residential MMC Phases',
  '4800001112 [ABYATONA] OXAGON Village Utility Culverts',
  '4800000731 [Thyssenkrupp] EBC Contract for Methanol-to-Gasoline Demo Plants',
  '4800001131 [Consortium - China Harbor, El Seif & Hassan Allam] Terminal T1 Infra & Building Work',
  '4800001271 [SAMA] Design, Build & Commission of MV 33/13.8 Kv SubStations in OXAGON',
  '4800001272 [AL Fahd Coastguard] Coast Guard Facilities Infrastructure and Building Work',
  '4800001322 [PPC] Supply & Installation of 1200 water pipeline - Water Supply to NGHP',
  '4200001383 [SAMA] ENOWA HV Corridor and TZE plot Earthworks',
  '4800001405 [Tamimi] OXAGON HIVE \u2013 Central Production Unit (CPU)',
  '4200000031 - WO - 029 [SAMA] Additional Earthworks at Zone E',
  '4800001440 [RPCO] SOUTHERN PLOTS ROADS NETWORK PACKAGE 1',
  '4200000029/026 - WADI Jubbah Permanent channel phase-1',
  '4800001134 [ABYATONA] Construction and Extension of Box Culvert under HWY 55.',
]

export const CONTRACTOR_OPTIONS: string[] = [
  'Al Fahd',
  'Shapoorji',
  'TAMIMI-AMT',
  'Archirodon',
  'TDP',
  'SIBS',
  'ABYATONA',
  'Thyssenkrupp',
  'Consortium - China Harbor, El Seif & Hassan Allam',
  'SAMA',
  'PPC',
  'RPCO',
  'NBC',
]

// Exact ordered header row for the exported importable file.
export const EXPORT_COLUMNS: string[] = [
  'CS \\ Approval Process Level',
  'Type',
  'Was there a fire?',
  'Did a person suffer an injury or illness?',
  'Was the environment impacted?',
  'Classification',
  'Site',
  'Contractor',
  'CS \\ Specific Area',
  'Latitude',
  'Longitude',
  'Event Date',
  'Reported Date',
  'UR \\ Work-related',
  'UR \\ Impacted Party',
  'Leadership Member Name',
  'Attendees',
  'Notify attendees by email',
  'Event Description',
  'Conditions',
  'Significant Hazard',
  'Was this a Repeat Incident?',
  'Immediate Corrective Actions',
  'UR  \\ Stop Work',
  'UR \\ Stop Work Details',
  'UR \\ Further Corrective Action Required?',
  'Attachments',
  'UR \\ Contractor Reviewer',
  'UR \\ Reviewer',
  'CS \\ Contractor Investigator',
  'UR \\ Lead Investigator',
  'UR \\ Validator',
  'UR \\ Approver',
  'Created By',
]
